\connect ssbu_tournament

CREATE USER SSBU_ADMIN WITH ENCRYPTED PASSWORD 'password';

GRANT CONNECT ON DATABASE ssbu_tournament TO SSBU_ADMIN;

GRANT USAGE ON SCHEMA public TO SSBU_ADMIN;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO SSBU_ADMIN;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO SSBU_ADMIN;